# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: slack-notifier
  description: Command line utility to send messages with attachments to Slack channels via Incoming Webhooks
  homepage: https://cloudposse.com/accelerate
  topics: ""
