name: "docker"
on:
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'

  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@1.15.1
        with:
          registry: ghcr.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          platforms: linux/amd64,linux/arm64

  release:
    if: github.event_name == 'push'
    needs: build-and-push
    uses: cloudposse/.github/.github/workflows/shared-go-auto-release.yml@main
    with:
      publish: true
    secrets: inherit